### ISSUE TITLE
yarn 3.2.1 script is not included in the repository

### ISSUE THREAD

**Issue by yshrsmz** [jpmonette/feed#180]
**Describe the bug**

When trying to install dependencies with yarn, I see error below:

```
Internal Error: The "yarn-path" option has been set (in /Users/yshrsmz/repos/github.com/yshrsmz/feed/.yarnrc.yml), but the specified location doesn't exist (/Users/yshrsmz/repos/github.com/yshrsmz/feed/.yarn/releases/yarn-3.2.1.cjs).
    at i (/Users/yshrsmz/.node/corepack/yarn/3.2.1/yarn.js:449:11811)
    at async r (/Users/yshrsmz/.node/corepack/yarn/3.2.1/yarn.js:449:10914)
```

This happens because the repo does not include `.yarn/releases/yarn-3.2.1.cjs`.

https://yarnpkg.com/getting-started/qa/#which-files-should-be-gitignored

According to the yarn documentation, we should add these lines to `.gitignore`, and commit some files in `.yarn` directory.

```
.pnp.*
.yarn/*
!.yarn/patches
!.yarn/plugins
!.yarn/releases
!.yarn/sdks
!.yarn/versions
```

**To Reproduce**

1. clone the repo
2. run `yarn install`
3. see error

**Expected behavior**

**Actual behavior**
A clear and concise description of what is the actual outcome.

**Screenshots**

**Versions (please complete the following information):**
 - NodeJS: 16.17.0
 - TypeScript: 
 - npm/yarn:
 - feed:

**Additional context**

**Comment by yshrsmz** [comment]
@jpmonette I've opened #181 to fix the issue. please take a look.
